version: '3.8'

services:
  wordpress:
    image: wordpress:php8.3-fpm-alpine
    container_name: wordpress_008
    restart: always
    depends_on:
      - db
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=admin
      - WORDPRESS_DB_PASSWORD=rMxhdpyKxjyk2h4etSsZ1hKxa91NVRpgMZUJcAjPLnY=
      - WORDPRESS_DB_NAME=wordpressdb
      - WORDPRESS_TABLE_PREFIX=wp_
    volumes:
      - ./wordpress/html:/var/www/html
      - ./wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - wordpress-network

  nginx:
    image: nginx:latest
    container_name: nginx_008
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./wordpress/html:/var/www/html:ro
    depends_on:
      - wordpress
    networks:
      - wordpress-network

  db:
    image: mysql:5.7
    container_name: db_008
    restart: always
    environment:
      - MYSQL_DATABASE=wordpressdb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=rMxhdpyKxjyk2h4etSsZ1hKxa91NVRpgMZUJcAjPLnY=
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - wordpress-network

networks:
  wordpress-network:
